version: '3.3'

services:
    django:
      image: zhkh_django
      build: 
        context: .
        dockerfile: ./app/house_zhkh_core/Dockerfile
      depends_on:
        - db

    fastapi:
      image: zhkh_fastapi
      build: 
        context: .
        dockerfile: ./app/house_zhkh_core/Dockerfile
      depends_on:
        - db

    db:
      image: postgres15
      container_name: postgres_db
      restart: always
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    redis:
      image: redis:alpine
      container_name: redis_broker
      restart: always
      ports:
        - "6379:6379"

    celery:
      build: .
      container_name: celery_worker
      restart: always
      depends_on:
        - redis
      env_file:
        - .env
      command: ["./venv/bin/celery", "-A", "tasks", "worker", "--loglevel=info"]

    flower:
      image: mher/flower
      container_name: celery_flower
      restart: always
      depends_on:
        - redis
        - celery
      env_file:
        - .env
      ports:
        - "5555:5555"
      command: ["flower", "--broker=redis://redis:6379/0"]

    elk:build: path

volumes:
  postgres_data: